
title: Enes Başpınar
email: enesbaspinar07@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bu blog, iyidir hoşdur ancak hiç bir şekilde profesyonellik içermemektedir.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://baspinarenes.github.io/ # the base hostname & protocol for your site, e.g. http://example.com

icon: assets/img/icon.jpg

twitter_username: enesbaspinar0
github_username:  baspinarenes
linkedin_username: enesbaspinar

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: pretty
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-autoprefixer

sass:
  sass_dir: _sass
  style: compressed